const a = [
  {
    title: "جلسه اول: معرفی کسب و کار",
    date: "1402-11-12",
    startTime: "10:00",
    endTime: "14:00",
    mentor: {
      id: 25,
      slug: "shahin-ghadiri",
      title_fa: "شاهین غدیری",
      title_en: "Shahin Ghadiri",
      image: "/uploads/mentors/images/1699689356.jpg",
      role: "ارزیاب ارشد کسب‌وکارهای نوپا",
    },
    sessionLink: "0",
    sessionType: "جلسه آموزشی",
    sessionTopics: ["معرفی استارتاپ و مراحل موجود در هر کسب‌وکار"],
  },
  {
    title: "جلسه دوم: ساختن ایده",
    date: "1402-11-19",
    startTime: "10:00",
    endTime: "14:00",
    mentor: {
      id: 25,
      slug: "shahin-ghadiri",
      title_fa: "شاهین غدیری",
      title_en: "Shahin Ghadiri",
      image: "/uploads/mentors/images/1699689356.jpg",
      role: "ارزیاب ارشد کسب‌وکارهای نوپا",
    },
    sessionLink: "0",
    sessionType: "جلسه آموزشی",
    sessionTopics: ["یافتن ایده قابل اجرا"],
  },
  {
    title: "جلسه سوم: شناسایی بازار هدف",
    date: "1402-11-26",
    startTime: "10:00",
    endTime: "14:00",
    mentor: {
      id: 25,
      slug: "shahin-ghadiri",
      title_fa: "شاهین غدیری",
      title_en: "Shahin Ghadiri",
      image: "/uploads/mentors/images/1699689356.jpg",
      role: "ارزیاب ارشد کسب‌وکارهای نوپا",
    },
    sessionLink: "0",
    sessionType: "جلسه آموزشی",
    sessionTopics: ["نحوه محاسبه اندازه بازار هدف"],
  },
  {
    title: "جلسه چهارم: بیزینس پلن و بیزینس مدل",
    date: "1402-12-3",
    startTime: "10:00",
    endTime: "14:00",
    mentor: {
      id: 25,
      slug: "shahin-ghadiri",
      title_fa: "شاهین غدیری",
      title_en: "Shahin Ghadiri",
      image: "/uploads/mentors/images/1699689356.jpg",
      role: "ارزیاب ارشد کسب‌وکارهای نوپا",
    },
    sessionLink: "0",
    sessionType: "جلسه آموزشی",
    sessionTopics: ["معرفی طرح و برنامه‌ کسب‌وکار"],
  },
  {
    title: "جلسه پنجم: هم‌بنیان‌گذاری",
    date: "1402-12-10",
    startTime: "10:00",
    endTime: "25:00",
    mentor: {
      id: 25,
      slug: "shahin-ghadiri",
      title_fa: "شاهین غدیری",
      title_en: "Shahin Ghadiri",
      image: "/uploads/mentors/images/1699689356.jpg",
      role: "ارزیاب ارشد کسب‌وکارهای نوپا",
    },
    sessionLink: "0",
    sessionType: "حضوری",
    sessionTopics: [
      "ویژگی هم‌بنیان‌گذاران خوب",
      "معرفی طرح و برنامه‌ کسب‌وکار",
    ],
  },
  {
    title: "جلسه ششم: مدیریت محصول",
    date: "1402-12-17",
    startTime: "10:00",
    endTime: "14:00",
    mentor: {
      id: 25,
      slug: "shahin-ghadiri",
      title_fa: "شاهین غدیری",
      title_en: "Shahin Ghadiri",
      image: "/uploads/mentors/images/1699689356.jpg",
      role: "ارزیاب ارشد کسب‌وکارهای نوپا",
    },
    sessionLink: "0",
    sessionType: "جلسه آموزشی",
    sessionTopics: ["MVP", "نحوه لانچ محصول"],
  },
];
